resource_group_name     = "azure-provisioning"
subnet_id               = "/subscriptions/7731a4d7-8fd3-4683-96a7-5d68a2adb50e/resourceGroups/azure-provisioning/providers/Microsoft.Network/virtualNetworks/vm-vnet/subnets/vm-subnet"
admin_username          = "geraldineadmin"
admin_password          = "P@ssw0rd1234!"
boot_diag_storage_uri = "https://diaggeraldinestorage.blob.core.windows.net/"
